name: CI

on:
  pull_request:
    branches: [master]

jobs:
  changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}

      - name: "Comment Changelog On PR"
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{steps.build_changelog.outputs.changelog }}
